FROM golang:1.24 AS migrate
WORKDIR /app
COPY .migrations /app/.migrations
RUN go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
RUN /go/bin/migrate -path .migrations -database=sqlite3://assets.db up

FROM oven/bun:1.3 AS builder
WORKDIR /app
COPY . .
COPY --from=migrate /app/assets.db ./assets.db
RUN bun install
RUN bun run check

ENV ASSETS_APP="./public"
ENV ASSETS_PORT=4020

RUN bun run backend:dev & echo $! >/tmp/backend.pid
RUN bun test
