name: BUILD-AND-TEST
run-name: ${{ gitea.actor }} is building and running tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test-code:
    runs-on: ubuntu-latest
    steps:
      - name: CHECK-OUT
        uses: actions/checkout@v4
      - name: SETUP GO
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      - name: INSTALL DEPENDENCIES
        run: |
          go mod download
      - name: RUN TESTS
        run: |
          make test
      - name: BUILD
        run: |
          make build
