name: BUILD-AND-TEST
run-name: ${{ gitea.actor }} is building and running tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build-and-test-code:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4
      - name: INSTALL BUN
        uses: oven-sh/setup-bun@v2
      - name: INSTALL DEPENDENCIES
        run: |
          bun install
      - name: RUN CHECKS
        run: |
          bun run check
