name: RELEASE-DOCKER-CONTAINER
run-name: ${{ gitea.actor }} building and pushing docker container
on:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: LOGIN TO RASPI DOCKER
        uses: docker/login-action@v3
        with:
          registry: raspi4:6363
          username: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: PULL & TAG
        run: |
          docker pull raspi4:6363/darkruby/assets:latest
          docker tag raspi4:6363/darkruby/assets:latest ghcr.io/venil7/assets:latest
      - name: LOGIN TO GITHUB DOCKER
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: venil7
          password: ${{ secrets.GTHB_CR_TOKEN }}
      - name: PUSH
        run: |
          docker push ghcr.io/venil7/assets:latest
