name: BUILD-AND-TEST
run-name: ${{ gitea.actor }} is running migrations
on:
  push:
    branches:
      - master

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: CHECK-OUT
        uses: actions/checkout@v4
      - name: SETUP GO
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      - name: RUN MIGRATION
        run: |
          go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
          # ~/go/bin/migrate -path ./.migrations -database=sqlite3://assets.db up
          make migrate
